<?php

########################################################################
# Extension Manager/Repository config file for ext: "countrymanager"
#
# Auto generated by Extension Builder 2012-10-31
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Typo3 Country Manager',
	'description' => 'Managing countries and languages was never an easy task with Typo3. Typo3 Country Manager aims to fix this.',
	'category' => 'plugin',
	'author' => 'Noel Bossart',
	'author_email' => 'n.company at me dot com',
	'author_company' => 'www.noelboss.ch',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.7',
			'static_info_tables' => '2.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>